'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {effectLabel,skills,stages,type SkillEffect} from '../lib/gameData';

type Enemy={g:THREE.Group;hp:number;max:number;boss:boolean;type:string;alive:boolean;cool:number;hitFlash:number;stagger:number;phase:number};
type Projectile={g:THREE.Mesh;v:THREE.Vector3;damage:number;life:number;enemy?:boolean;boss?:boolean};
type Fx={g:THREE.Object3D;life:number;max:number;kind:'burst'|'ring'|'trail'|'text'};
const SAVE='shadowfall-save';
class AudioEngine{ctx:AudioContext|null=null;master:GainNode|null=null;ambient:OscillatorNode|null=null;wake(){try{const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return null;if(!this.ctx){this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.055;this.master.connect(this.ctx.destination)}if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx}catch{return null}}play(freq:number,duration=.1,type:OscillatorType='square',volume=1){const c=this.wake();if(!c||!this.master)return;const o=c.createOscillator(),g=c.createGain(),now=c.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0001,.035*volume),now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(this.master);o.start(now);o.stop(now+duration+.02)}startAmbient(freq:number){const c=this.wake();if(!c||this.ambient||!this.master)return;const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=.008;o.connect(g);g.connect(this.master);o.start();this.ambient=o}stop(){try{this.ambient?.stop()}catch{}this.ambient=null}}
const audio=new AudioEngine();
function clamp01(v:number){return Math.max(0,Math.min(1,v))}
function makeTextTexture(text:string,color='#ffffff'){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d')!;x.clearRect(0,0,256,64);x.font='700 32px Arial';x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.shadowColor=color;x.shadowBlur=12;x.fillText(text,128,32);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
export default function Game(){
 const mount=useRef<HTMLDivElement>(null),keys=useRef<Record<string,boolean>>({}),touch=useRef({x:0,y:0});
 const [screen,setScreen]=useState<'play'|'map'|'skills'>('play'),[stage,setStage]=useState(1),[xp,setXp]=useState(0),[shards,setShards]=useState(20),[kills,setKills]=useState(0),[stageKills,setStageKills]=useState(0),[hp,setHp]=useState(100),[levels,setLevels]=useState<Record<number,number>>({1:1}),[toast,setToast]=useState(''),[combo,setCombo]=useState(0);
 const levelsRef=useRef(levels),hpRef=useRef(hp);useEffect(()=>{levelsRef.current=levels},[levels]);useEffect(()=>{hpRef.current=hp},[hp]);
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(SAVE)||'null');if(d){setStage(d.stage||1);setXp(d.xp||0);setShards(d.shards??20);setKills(d.kills||0);setStageKills(d.stageKills||0);setHp(d.hp??100);setLevels(d.levels||{1:1})}}catch{}},[]);
 useEffect(()=>{localStorage.setItem(SAVE,JSON.stringify({stage,xp,shards,kills,stageKills,hp,levels}))},[stage,xp,shards,kills,stageKills,hp,levels]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;audio.wake();if(e.key==='Escape')setScreen('play')},u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);
 const stat=(effect:SkillEffect)=>Object.entries(levels).reduce((n,[id,lv])=>n+(skills[+id-1]?.effect===effect?lv*skills[+id-1].value:0),0);
 const branchLv=(branch:string)=>skills.filter(s=>s.branch===branch).reduce((n,s)=>n+(levels[s.id]||0),0);
 const buy=(id:number)=>{const s=skills[id-1],lv=levels[id]||0;if(lv>=s.max||shards<s.cost||(s.prereq!==null&&(levels[s.prereq]||0)<1))return;setShards(v=>v-s.cost);setLevels(v=>({...v,[id]:lv+1}));audio.play(880,.12,'sine',1);setToast(`${s.name}  ·  LV.${lv+1}`);setTimeout(()=>setToast(''),900)};
 useEffect(()=>{if(screen!=='play'||!mount.current)return;const el=mount.current,cfg=stages[stage-1],scene=new THREE.Scene();scene.background=new THREE.Color(0x050711);scene.fog=new THREE.FogExp2(0x070a16,.032);const camera=new THREE.PerspectiveCamera(48,1,.1,140),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;el.appendChild(renderer.domElement);
 const hemi=new THREE.HemisphereLight(0xb9c6ff,0x10121c,1.45);scene.add(hemi);const sun=new THREE.DirectionalLight(0xdde5ff,3.1);sun.position.set(5,12,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-18;scene.add(sun);const glow=new THREE.PointLight(cfg.color,18,24);glow.position.set(-4,4,-4);scene.add(glow);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(34,26),new THREE.MeshStandardMaterial({color:0x0d1220,roughness:.86,metalness:.16}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(34,34,cfg.color,0x151a2a);grid.material.transparent=true;grid.material.opacity=.16;scene.add(grid);
 const player=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.43,1.0,6,10),new THREE.MeshStandardMaterial({color:0xdce7ff,metalness:.76,roughness:.22}));const chest=new THREE.Mesh(new THREE.BoxGeometry(.72,.48,.42),new THREE.MeshStandardMaterial({color:0x5f6f8d,metalness:.82,roughness:.2}));const helm=new THREE.Mesh(new THREE.SphereGeometry(.46,16,10),new THREE.MeshStandardMaterial({color:0x111729,metalness:.9,roughness:.16,emissive:0x101a40}));const visor=new THREE.Mesh(new THREE.BoxGeometry(.34,.06,.08),new THREE.MeshBasicMaterial({color:cfg.color}));const shoulderL=new THREE.Mesh(new THREE.SphereGeometry(.2,10,8),new THREE.MeshStandardMaterial({color:0x8294b8,metalness:.7})),shoulderR=shoulderL.clone();const bootL=new THREE.Mesh(new THREE.BoxGeometry(.24,.42,.32),new THREE.MeshStandardMaterial({color:0x29334a,metalness:.75})),bootR=bootL.clone();const guard=new THREE.Mesh(new THREE.BoxGeometry(.34,.12,.12),new THREE.MeshStandardMaterial({color:0xf1c75b,metalness:.9}));const blade=new THREE.Mesh(new THREE.BoxGeometry(.12,1.55,.09),new THREE.MeshStandardMaterial({color:0xd6e5ff,emissive:cfg.color,emissiveIntensity:.65,metalness:.94,roughness:.13}));body.position.y=1.05;chest.position.set(0,1.25,.05);helm.position.y=1.9;helm.scale.y=.82;visor.position.set(0,1.94,.42);shoulderL.position.set(-.47,1.38,0);shoulderR.position.set(.47,1.38,0);bootL.position.set(-.22,.27,0);bootR.position.set(.22,.27,0);guard.position.set(.72,1.72,.05);blade.position.set(.72,1.02,.05);blade.rotation.z=-.48;[body,chest,helm,shoulderL,shoulderR,bootL,bootR,guard,blade].forEach(m=>m.castShadow=true);player.add(body,chest,helm,visor,shoulderL,shoulderR,bootL,bootR,guard,blade);scene.add(player);
 const playerShadow=new THREE.Mesh(new THREE.CircleGeometry(.72,32),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.42,depthWrite:false}));playerShadow.rotation.x=-Math.PI/2;playerShadow.position.y=.025;player.add(playerShadow);
 const enemies:Enemy[]=[];const makeEnemy=(i:number,boss=false)=>{const type=boss?'boss':i%7===0?'brute':i%5===0?'caster':'stalker',g=new THREE.Group(),base=boss?cfg.color:[0xc43b70,0x8c4dff,0x2db7aa,0xff7048][i%4],mat=new THREE.MeshStandardMaterial({color:base,roughness:.4,metalness:.42,emissive:boss?base:0,emissiveIntensity:boss?.28:0});const core=new THREE.Mesh(boss?new THREE.IcosahedronGeometry(1.25,1):type==='brute'?new THREE.DodecahedronGeometry(.72,1):new THREE.IcosahedronGeometry(.55,1),mat);core.position.y=boss?1.35:.62;core.castShadow=true;g.add(core);if(type==='stalker'){for(const side of[-1,1]){const fin=new THREE.Mesh(new THREE.ConeGeometry(.11,.72,6),new THREE.MeshBasicMaterial({color:base}));fin.position.set(side*.45,.7,0);fin.rotation.z=side*.8;g.add(fin)}}if(type==='brute'){for(const side of[-1,1]){const horn=new THREE.Mesh(new THREE.ConeGeometry(.17,.48,6),new THREE.MeshStandardMaterial({color:0x242a39,metalness:.8}));horn.position.set(side*.42,1.12,0);horn.rotation.z=side*.55;g.add(horn)}}if(type==='caster'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.055,8,24),new THREE.MeshBasicMaterial({color:cfg.color}));ring.rotation.x=Math.PI/2;ring.position.y=.65;g.add(ring);const orb=new THREE.Mesh(new THREE.SphereGeometry(.14,10,8),new THREE.MeshBasicMaterial({color:cfg.color}));orb.position.y=1.35;g.add(orb)}if(boss){for(let n=0;n<2;n++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.55+n*.32,.045,8,32),new THREE.MeshBasicMaterial({color:cfg.color,transparent:true,opacity:.7}));ring.rotation.x=Math.PI/2;ring.position.y=.15+n*.45;g.add(ring)}}g.position.set(((i*3.7)%17)-8.5,0,-((i*2.15)%10)-1);scene.add(g);const max=boss?18:type==='brute'?4:type==='caster'?2:1;enemies.push({g,hp:max,max,boss,type,alive:true,cool:1+Math.random(),hitFlash:0,stagger:0,phase:1})};
 for(let i=0;i<Math.min(16,cfg.enemies);i++)makeEnemy(i);if(cfg.boss)makeEnemy(99,true);
 const fx:Fx[]=[];const projectiles:Projectile[]=[];let shake=0,hitStop=0,comboCount=0,comboTimer=0,stageDone=false;
 const addFx=(g:THREE.Object3D,life:number,kind:Fx['kind'])=>{fx.push({g,life,max:life,kind});fxGroup.add(g)};const fxGroup=new THREE.Group();scene.add(fxGroup);
 const burst=(pos:THREE.Vector3,color:number,count=9,scale=.045)=>{for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(scale,5,5),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos);m.userData.v=new THREE.Vector3((Math.random()-.5)*.16,.04+Math.random()*.13,(Math.random()-.5)*.16);addFx(m,.42,'burst')}};
 const ringFx=(pos:THREE.Vector3,color:number,radius:number)=>{const r=new THREE.Mesh(new THREE.RingGeometry(radius*.72,radius,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false}));r.rotation.x=-Math.PI/2;r.position.copy(pos);r.position.y=.04;addFx(r,.55,'ring')};
 const trailFx=(a:THREE.Vector3,b:THREE.Vector3,color:number)=>{const d=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(.025,.11,d.length,6),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.65,depthWrite:false}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());addFx(m,.16,'trail')};
 const damageText=(pos:THREE.Vector3,value:number,crit=false)=>{const s=new THREE.Sprite(new THREE.SpriteMaterial({map:makeTextTexture(`${crit?'CRIT ':''}${Math.round(value)}`,crit?'#ffd66b':'#ffffff'),transparent:true,depthWrite:false}));s.position.copy(pos);s.position.y+=1.1;s.scale.set(.9,.23,1);s.userData.v=new THREE.Vector3((Math.random()-.5)*.01,.018,0);addFx(s,.65,'text')};
 const spawnProjectile=(from:THREE.Vector3,to:THREE.Vector3,color:number,damage:number,enemy=false,boss=false)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(enemy?.11:.13,8,8),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(from);scene.add(m);const d=to.clone().sub(from).normalize();projectiles.push({g:m,v:d.multiplyScalar(enemy?.105:.18),damage,life:enemy?3:2.4,enemy,boss})};
 const resize=()=>{const r=el.getBoundingClientRect();renderer.setSize(Math.max(320,r.width),Math.max(320,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};resize();addEventListener('resize',resize);audio.startAmbient(55+stage*1.5);
 const statNow=(effect:SkillEffect)=>Object.entries(levelsRef.current).reduce((n,[id,lv])=>n+(skills[+id-1]?.effect===effect?lv*skills[+id-1].value:0),0),branchNow=(b:string)=>skills.filter(s=>s.branch===b).reduce((n,s)=>n+(levelsRef.current[s.id]||0),0);
 let raf=0,t=0,last=performance.now(),lastDmg=0,lastAtk=0,qCd=0,eCd=0,rCd=0,invuln=0,attackAnim=0;
 const damageEnemy=(hit:Enemy,amount:number,crit=false)=>{if(!hit.alive||hit.stagger>0)return;hit.hp-=amount;hit.hitFlash=.12;hit.stagger=crit?.13:.07;hit.g.scale.setScalar(1.12);shake=Math.max(shake,crit?.16:.07);hitStop=Math.max(hitStop,crit?.045:.025);damageText(hit.g.position,amount,crit);burst(hit.g.position,crit?0xffd66b:cfg.color,crit?18:10,crit?.06:.045);audio.play(crit?120:210,crit?.08: .055,crit?'sawtooth':'square',crit?1.4:.8);setTimeout(()=>{if(hit.alive)hit.g.scale.setScalar(1)},75);if(hit.hp<=0){hit.alive=false;comboCount++;comboTimer=2.2;setCombo(comboCount);setKills(v=>v+1);setStageKills(v=>v+1);setXp(v=>v+Math.round((6+stage)*xpMult()));setShards(v=>v+(hit.boss?9:1));burst(hit.g.position,hit.boss?0xffffff:cfg.color,hit.boss?32:20,hit.boss?.09:.07);ringFx(hit.g.position,hit.boss?0xffffff:cfg.color,hit.boss?2:.85);audio.play(hit.boss?70:520,hit.boss?.3:.12,hit.boss?'sawtooth':'square',hit.boss?1.5:1);hit.g.userData.death=.48;if(hit.boss)setToast('BOSS DEFEATED')}};
 const xpMult=()=>1+statNow('xp')/100;
 const attack=()=>{const now=performance.now();if(now-lastAtk<210)return;lastAtk=now;attackAnim=.22;audio.play(190,.07,'sawtooth');let hit:Enemy|undefined,best=2.6+statNow('range');for(const e of enemies)if(e.alive){const d=e.g.position.distanceTo(player.position);if(d<best){best=d;hit=e}}if(!hit)return;const crit=Math.random()<Math.min(.6,statNow('crit')/100);const amount=(1+statNow('damage')/100)*(crit?2:1)*(1+branchNow('BLADE')*.025);damageEnemy(hit,amount,crit);trailFx(player.position.clone().setY(1.25),hit.g.position.clone().setY(.75),cfg.color)};
 const ability=(key:'q'|'e'|'r')=>{if(key==='q'&&qCd>0||key==='e'&&eCd>0||key==='r'&&rCd>0)return;const nearest=enemies.filter(e=>e.alive).sort((a,b)=>a.g.position.distanceTo(player.position)-b.g.position.distanceTo(player.position))[0];if(key==='q'){qCd=Math.max(2.4,4.5-branchNow('BLADE')*.08);attackAnim=.35;ringFx(player.position,cfg.color,2.3);for(const e of enemies)if(e.alive&&e.g.position.distanceTo(player.position)<2.8)damageEnemy(e,3.5*(1+branchNow('BLADE')*.06));audio.play(260,.22,'sawtooth',1.2)}else if(key==='e'){eCd=Math.max(1.2,2.4-branchNow('ARCANE')*.04);if(nearest){spawnProjectile(player.position.clone().setY(1),nearest.g.position.clone().setY(.7),0x9f7cff,3*(1+branchNow('ARCANE')*.06));audio.play(740,.16,'sine')}}else{rCd=Math.max(6,10-branchNow('SHADOW')*.12);ringFx(player.position,0xffffff,4.4);for(const e of enemies)if(e.alive&&e.g.position.distanceTo(player.position)<4.8)damageEnemy(e,7*(1+branchNow('SHADOW')*.05));invuln=.8;shake=.22;audio.play(90,.35,'sawtooth',1.4)}};
 const loop=()=>{const now=performance.now(),dt=Math.min(.035,(now-last)/1000);last=now;t+=dt;qCd-=dt;eCd-=dt;rCd-=dt;invuln=Math.max(0,invuln-dt);shake=Math.max(0,shake-dt*2.8);comboTimer=Math.max(0,comboTimer-dt);if(comboTimer<=0&&comboCount){comboCount=0;setCombo(0)}if(hitStop>0){hitStop-=dt;renderer.render(scene,camera);raf=requestAnimationFrame(loop);return}
 let dx=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0)+touch.current.x,dz=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0)+touch.current.y,len=Math.hypot(dx,dz)||1;dx/=len;dz/=len;const dash=!!keys.current.shift;keys.current.shift=false;const v=dash?.2:(.075+statNow('speed')/1000);if(dash){invuln=.28;shake=.08;audio.play(420,.08,'sawtooth');trailFx(player.position.clone().setY(.8),player.position.clone().setY(.8).add(new THREE.Vector3(-dx,0,-dz)),cfg.color)}player.position.x=THREE.MathUtils.clamp(player.position.x+dx*v,-13,13);player.position.z=THREE.MathUtils.clamp(player.position.z+dz*v,-9,8);if(dx||dz)player.rotation.y=Math.atan2(dx,dz);body.position.y=1.05+Math.sin(t*(dx||dz?10:4))*.025;bootL.rotation.x=Math.sin(t*10)*.12*(dx||dz?1:0);bootR.rotation.x=-bootL.rotation.x;if(keys.current[' ']||keys.current.j){keys.current[' ']=false;keys.current.j=false;attack()}if(keys.current.q){keys.current.q=false;ability('q')}if(keys.current.e){keys.current.e=false;ability('e')}if(keys.current.r){keys.current.r=false;ability('r')}
 if(attackAnim>0){attackAnim-=dt;blade.rotation.z=-.48+Math.sin((.35-attackAnim)*22)*.95}else blade.rotation.z=THREE.MathUtils.lerp(blade.rotation.z,-.48,.18);
 for(const e of enemies)if(e.alive){if(e.userData.death){e.userData.death-=dt;e.g.scale.setScalar(Math.max(.04,e.userData.death/.48));e.g.rotation.y+=dt*7;if(e.userData.death<=0){e.g.visible=false;e.userData.death=0}continue}e.stagger=Math.max(0,e.stagger-dt);const ex=player.position.x-e.g.position.x,ez=player.position.z-e.g.position.z,d=Math.hypot(ex,ez)||1;let f=e.boss?.006:e.type==='brute'?.008:e.type==='caster'?.0045:.012;if(e.stagger>0)f=0;if(e.type==='stalker'&&d<3){const orbit=Math.sin(t*2+e.g.position.x)*.035;e.g.position.x+=(-ez/d*f)+orbit;e.g.position.z+=((ex/d)*f)}else if(e.type==='caster'&&d<3.2){e.g.position.x-=ex/d*f*1.8;e.g.position.z-=ez/d*f*1.8}else{e.g.position.x+=ex/d*f;e.g.position.z+=ez/d*f}e.g.position.y=Math.sin(t*2+e.g.position.x)*.08;e.g.rotation.y+=dt*(e.type==='brute'?.5:1.5);if(e.type==='caster'&&e.cool<=0&&d<8){e.cool=2.1;spawnProjectile(e.g.position.clone().setY(1),player.position.clone().setY(1),0xff7048,3,true);ringFx(e.g.position,0xff7048,1)}if(e.boss&&e.cool<=0){e.cool=3.8;e.phase=e.hp<e.max*.5?2:1;ringFx(e.g.position,cfg.color,e.phase===2?4:3.2);for(let a=0;a<(e.phase===2?12:8);a++){const ang=a*Math.PI/(e.phase===2?6:4);spawnProjectile(e.g.position.clone().setY(1.2),e.g.position.clone().add(new THREE.Vector3(Math.sin(ang),0,Math.cos(ang))),cfg.color,e.phase===2?6:5,true,true)}audio.play(75,.5,'sawtooth',1.2)}e.cool-=dt;if(d<1.35&&performance.now()-lastDmg>450&&invuln<=0){lastDmg=performance.now();const incoming=(e.boss?8:e.type==='brute'?5:3)*(1-Math.min(.7,statNow('armor')/100));setHp(v=>Math.max(0,v-incoming));shake=Math.max(shake,.09);audio.play(110,.08,'square')}}
 for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i],prev=p.g.position.clone();p.g.position.add(p.v);p.life-=dt;trailFx(prev,p.g.position,p.enemy?(p.boss?cfg.color:0xff7048):0x9f7cff);if(p.enemy&&p.g.position.distanceTo(player.position)<.8){if(invuln<=0)setHp(v=>Math.max(0,v-Math.max(1,p.damage*(1-Math.min(.7,statNow('armor')/100)))));burst(p.g.position,p.boss?cfg.color:0xff7048,12,.05);scene.remove(p.g);projectiles.splice(i,1);continue}if(!p.enemy){let hit:Enemy|undefined;for(const e of enemies)if(e.alive&&!e.userData.death&&e.g.position.distanceTo(p.g.position)<.85){hit=e;break}if(hit){damageEnemy(hit,p.damage,false);burst(p.g.position,0x9f7cff,14,.055);scene.remove(p.g);projectiles.splice(i,1);continue}}if(p.life<=0){scene.remove(p.g);projectiles.splice(i,1)}}
 for(let i=fx.length-1;i>=0;i--){const f=fx[i];f.life-=dt;const o=f.g,u=o.userData;if(u.v)o.position.addScaledVector(u.v,dt*60);const k=clamp01(f.life/f.max);if(f.kind==='ring'){o.scale.multiplyScalar(1+dt*2);(o as THREE.Mesh).material.opacity=k*.7}else if(f.kind==='burst'){o.scale.setScalar(k);(o as THREE.Mesh).material.opacity=k}else if(f.kind==='trail'){(o as THREE.Mesh).material.opacity=k*.65}else{o.position.y+=dt*.7;o.scale.multiplyScalar(1+dt*.25);(o as THREE.Sprite).material.opacity=k}if(f.life<=0){fxGroup.remove(o);if((o as THREE.Sprite).material?.map)(o as THREE.Sprite).material.map.dispose();fx.splice(i,1)}}
 if(hpRef.current<=0){setHp(100);hpRef.current=100;player.position.set(0,0,4);setCombo(0);comboCount=0;audio.play(300,.25,'sine');setToast('RECOVERED');setTimeout(()=>setToast(''),900)}
 const alive=enemies.filter(e=>e.alive).length;if(alive===0&&!stageDone){stageDone=true;setToast(stage===34?'CAMPAIGN COMPLETE':'SECTOR CLEAR');audio.play(stage===34?60:880,.35,'sine',1.3)}
 const target=new THREE.Vector3(player.position.x*.25,0,player.position.z*.16);const sx=(Math.random()-.5)*shake,sz=(Math.random()-.5)*shake;camera.position.lerp(new THREE.Vector3(target.x+sx,8.5+sx,11+target.z+sz),.045);camera.lookAt(target);renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);projectiles.forEach(p=>scene.remove(p.g));fx.forEach(f=>fxGroup.remove(f.g));audio.stop();renderer.dispose();el.innerHTML=''}},[screen,stage]);
 const need=stages[stage-1].enemies+(stages[stage-1].boss?1:0);const clear=()=>{if(stageKills<need){setToast(`DEFEAT ${need-stageKills} MORE TARGETS`);setTimeout(()=>setToast(''),1200);return}setShards(v=>v+stages[stage-1].reward);if(stage<34){setStage(v=>v+1);setStageKills(0);setXp(0);setHp(100);setToast('STAGE CLEAR');audio.play(880)}else{setToast('CAMPAIGN COMPLETE');audio.play(80,.4)}setTimeout(()=>setToast(''),1500)};
 return <main className="shell"><header><div><div className="brand">K3RITO // SHADOWFALL</div><div className="sub">3D ACTION RPG · SECTOR {String(stage).padStart(2,'0')} / 34 · {stages[stage-1].biome}</div></div><nav><button onClick={()=>setScreen('play')} className={screen==='play'?'active':''}>PLAY</button><button onClick={()=>setScreen('map')} className={screen==='map'?'active':''}>MAP</button><button onClick={()=>setScreen('skills')} className={screen==='skills'?'active':''}>SKILLS <b>120</b></button></nav></header>
 {screen==='play'&&<section className="game"><div className="hud"><span>HP <i>{Math.round(hp)}</i></span><span>XP <i>{xp}</i></span><span>SHARDS <i>{shards}</i></span><span>KILLS <i>{stageKills}/{need}</i></span>{combo>1&&<span>COMBO <i>x{combo}</i></span>}<span className="stage">DMG +{Math.round(stat('damage'))}% · SPD +{Math.round(stat('speed'))}% · ARM {Math.round(stat('armor'))}% · CRIT +{Math.round(stat('crit'))}%</span></div><div ref={mount} className={`threeGame hp${hp<30?' critical':''}`} onPointerDown={()=>audio.wake()} onTouchStart={e=>{audio.wake();const t=e.touches[0],r=e.currentTarget.getBoundingClientRect();touch.current={x:(t.clientX-r.left-r.width/2)/(r.width/2),y:(t.clientY-r.top-r.height/2)/(r.height/2)}}} onTouchEnd={()=>touch.current={x:0,y:0}}/><div className="touchControls"><button onTouchStart={()=>keys.current.shift=true}>DASH</button><button onTouchStart={()=>keys.current.j=true}>ATTACK</button><button onTouchStart={()=>keys.current.q=true}>Q</button><button onTouchStart={()=>keys.current.e=true}>E</button><button onTouchStart={()=>keys.current.r=true}>R</button></div><div className="actions"><button onClick={clear}>EXTRACT / CLEAR</button><button onClick={()=>setScreen('skills')}>OPEN SKILL TREE</button></div><div className="controls">WASD / ARROWS MOVE · SHIFT DASH · SPACE / J ATTACK · Q AOE · E ARC PROJECTILE · R SHADOW NOVA · TOUCH DRAG MOVE</div></section>}
 {screen==='map'&&<section className="panel"><h1>THE SHADOWFALL CAMPAIGN</h1><p>34 sectors · 8 biome themes · escalating enemies · 7 boss encounters.</p><div className="grid">{stages.map(s=><button key={s.id} disabled={s.id>stage} onClick={()=>{setStage(s.id);setStageKills(0);setScreen('play')}} className={s.id===stage?'selected':''}><strong>{String(s.id).padStart(2,'0')}</strong><span>{s.name}</span><small>{s.biome}{s.boss?' · BOSS':''}</small></button>)}</div></section>}
 {screen==='skills'&&<section className="panel skills"><div className="skillHead"><div><h1>ASCENSION MATRIX</h1><p>120 nodes · 12 branches · 5 levels. Upgrades modify combat and unlock active abilities.</p></div><strong>{shards} SHARDS</strong></div><div className="skillStats"><span>DMG +{Math.round(stat('damage'))}%</span><span>SPD +{Math.round(stat('speed'))}%</span><span>RANGE +{stat('range').toFixed(1)}</span><span>ARM +{Math.round(stat('armor'))}%</span><span>CRIT +{Math.round(stat('crit'))}%</span><span>XP +{Math.round(stat('xp'))}%</span></div><div className="skillGrid">{skills.map(s=>{const lv=levels[s.id]||0,locked=s.prereq!==null&&(levels[s.prereq]||0)<1;return <button key={s.id} disabled={locked||lv>=s.max||shards<s.cost} onClick={()=>buy(s.id)} className={`${lv?'owned ':''}${locked?'locked':''}`}><em>{String(s.id).padStart(3,'0')} · {s.branch}</em><b>{s.name}</b><span>{locked?'LOCKED':`+${s.value}${s.effect==='range'?'':'%'} ${effectLabel(s.effect)} · ${lv}/${s.max}`}</span><small>{lv>=s.max?'MAX':`${s.cost} ◆`}</small></button>})}</div></section>}
 {toast&&<div className="toast">{toast}</div>}<footer>AAA PASS · PROCEDURAL 3D · 34 SECTORS · 120 SKILLS · COMBO · STAGGER · CRITS · HIT STOP · CAMERA SHAKE · VFX · BOSS PHASES · WEB AUDIO · LOCAL SAVE · K3RITO</footer></main>;
}
