'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';

type Skill={id:number;name:string;branch:string;max:number;prereq:number|null;cost:number;effect:'damage'|'speed'|'armor'|'crit'|'range'|'xp'};
type Stage={id:number;name:string;biome:string;enemies:number;boss:boolean;reward:number;color:number};
const BRANCHES=['VOID','BLADE','ARCANE','RANGER','GUARDIAN','FROST','EMBER','STORM','SUMMON','ALCHEMY','SHADOW','ASCENSION'];
const NAMES=['Core','Edge','Pulse','Focus','Ward','Mastery','Surge','Echo','Fury','Apex'];
const EFFECTS=['damage','speed','range','armor','crit','xp'] as Skill['effect'][];
const skills:Skill[]=Array.from({length:120},(_,i)=>({id:i+1,name:`${BRANCHES[Math.floor(i/10)]} ${NAMES[i%10]}`,branch:BRANCHES[Math.floor(i/10)],max:5,prereq:i?i:null,cost:2+Math.floor(i*1.35),effect:EFFECTS[i%6]}));
const stageNames=['Ashfall Gate','Cinder Run','Gravewind','Black Furnace','Warden of Cinders','Moonlit Ruins','Silent Cloister','Silver Catacombs','Nocturne Bridge','Lunar Revenant','Crystal Vale','Glassroot','Prism Depths','Resonant Hollow','The Prism Tyrant','Obsidian Descent','Magma Veins','Dread Quarry','Infernal Keep','Obsidian Colossus','Skyward Steps','Cloud Bastion','Aether Gardens','Storm Spire','The Storm Regent','Null Frontier','Echoing Maw','Starless Sea','Eventide Crown','The Void Sovereign','Ascension Path','Crownless Hall','Godfall','K3RITO // ASCENSION'];
const biomes=['Ashen Fields','Ashen Fields','Ashen Fields','Ashen Fields','Ashen Fields','Moonlit Ruins','Moonlit Ruins','Moonlit Ruins','Moonlit Ruins','Moonlit Ruins','Crystal Vale','Crystal Vale','Crystal Vale','Crystal Vale','Crystal Vale','Obsidian Depths','Obsidian Depths','Obsidian Depths','Obsidian Depths','Obsidian Depths','Sky Citadel','Sky Citadel','Sky Citadel','Sky Citadel','Sky Citadel','Void Expanse','Void Expanse','Void Expanse','Void Expanse','Void Expanse','Ascension Sanctum','Ascension Sanctum','Ascension Sanctum','Ascension Sanctum'];
const colors=[0x7c5cff,0xff704d,0xb05cff,0xff4f72,0xffa045,0x6e7cff,0x55b8ff,0x8f7cff,0xb58cff,0x7b9cff,0x34d6c3,0x4eeaff,0x9d7cff,0x48c6ff,0xe4a4ff,0xff5a58,0xff8a3d,0xc74dff,0xff5f86,0xffb04a,0x6ea8ff,0x8fc6ff,0x6dffcf,0x9f8cff,0x72c8ff,0x7c5cff,0xc85cff,0x5c86ff,0xff5c9d,0xd17cff,0xffd36e,0xffb45c,0xff7c5c,0xffffff];
const stages:Stage[]=stageNames.map((name,i)=>({id:i+1,name,biome:biomes[i],enemies:7+(i%6)*2,boss:(i+1)%5===0||i===33,reward:25+i*9,color:colors[i]}));
function beep(f:number=440){try{const A=window.AudioContext||(window as any).webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.025;g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.13)}catch{}}
export default function Game(){
 const mount=useRef<HTMLDivElement>(null),keys=useRef<Record<string,boolean>>({}),touch=useRef({x:0,y:0});
 const [screen,setScreen]=useState<'play'|'map'|'skills'>('play'),[stage,setStage]=useState(1),[xp,setXp]=useState(0),[shards,setShards]=useState(20),[kills,setKills]=useState(0),[stageKills,setStageKills]=useState(0),[hp,setHp]=useState(100),[levels,setLevels]=useState<Record<number,number>>({1:1}),[toast,setToast]=useState('');
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('shadowfall-save')||'null');if(d){setStage(d.stage||1);setXp(d.xp||0);setShards(d.shards??20);setKills(d.kills||0);setStageKills(d.stageKills||0);setHp(d.hp??100);setLevels(d.levels||{1:1})}}catch{}},[]);
 useEffect(()=>{localStorage.setItem('shadowfall-save',JSON.stringify({stage,xp,shards,kills,stageKills,hp,levels}))},[stage,xp,shards,kills,stageKills,hp,levels]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(e.key==='Escape')setScreen('play')},u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);
 useEffect(()=>{if(screen!=='play'||!mount.current)return;const el=mount.current,cfg=stages[stage-1],scene=new THREE.Scene();scene.background=new THREE.Color(0x050711);scene.fog=new THREE.FogExp2(0x070a16,.035);const camera=new THREE.PerspectiveCamera(48,1,.1,120),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});camera.position.set(0,8.5,11);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0xb9c6ff,0x10121c,1.5));const dl=new THREE.DirectionalLight(0xdde5ff,3);dl.position.set(5,12,6);dl.castShadow=true;scene.add(dl);const pl=new THREE.PointLight(cfg.color,14,22);pl.position.set(-4,4,-4);scene.add(pl);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,24),new THREE.MeshStandardMaterial({color:0x0d1220,roughness:.85,metalness:.15}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(30,30,cfg.color,0x151a2a);grid.material.transparent=true;grid.material.opacity=.18;scene.add(grid);
 const player=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,1.05,6,10),new THREE.MeshStandardMaterial({color:0xdce7ff,metalness:.7,roughness:.28})),helm=new THREE.Mesh(new THREE.SphereGeometry(.46,16,10),new THREE.MeshStandardMaterial({color:0x12182a,metalness:.85,roughness:.2,emissive:0x101a40})),visor=new THREE.Mesh(new THREE.BoxGeometry(.34,.06,.08),new THREE.MeshBasicMaterial({color:cfg.color})),blade=new THREE.Mesh(new THREE.BoxGeometry(.12,1.55,.09),new THREE.MeshStandardMaterial({color:0xcfe2ff,emissive:cfg.color,emissiveIntensity:.5,metalness:.9}));body.position.y=1.05;helm.position.y=1.9;helm.scale.y=.82;visor.position.set(0,1.94,.42);blade.position.set(.72,1.25,.05);blade.rotation.z=-.48;[body,helm,blade].forEach(x=>x.castShadow=true);player.add(body,helm,visor,blade);scene.add(player);
 type E={g:THREE.Group;hp:number;max:number;boss:boolean;alive:boolean;type:string;cool:number};const enemies:E[]=[];const makeEnemy=(i:number,boss=false)=>{const type=boss?'boss':i%7===0?'brute':i%5===0?'caster':'stalker',g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:boss?cfg.color:[0xc43b70,0x8c4dff,0x2db7aa,0xff7048][i%4],roughness:.45,metalness:.3,emissive:boss?cfg.color:0,emissiveIntensity:boss?.22:0}),geo=boss?new THREE.IcosahedronGeometry(1.35,1):type==='brute'?new THREE.DodecahedronGeometry(.75,1):new THREE.IcosahedronGeometry(.55,1),core=new THREE.Mesh(geo,mat);core.position.y=boss?1.25:.62;core.castShadow=true;g.add(core);if(type==='caster'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.75,.055,8,24),new THREE.MeshBasicMaterial({color:cfg.color}));ring.rotation.x=Math.PI/2;ring.position.y=.65;g.add(ring)}g.position.set(((i*3.7)%16)-8,0,-((i*2.15)%9)-1);scene.add(g);enemies.push({g,hp:boss?10:type==='brute'?2:1,max:boss?10:type==='brute'?2:1,boss,alive:true,type,cool:0})};
 for(let i=0;i<Math.min(16,cfg.enemies);i++)makeEnemy(i);if(cfg.boss)makeEnemy(99,true);
 const props=new THREE.Group();for(let i=0;i<26;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.34+(i%3)*.13),new THREE.MeshStandardMaterial({color:cfg.color,roughness:.9,transparent:true,opacity:.25}));rock.scale.y=.5+(i%5)*.27;rock.position.set(((i*5.1)%27)-13.5,rock.scale.y*.35,((i*3.7)%19)-9);rock.castShadow=true;props.add(rock)}scene.add(props);
 const resize=()=>{const r=el.getBoundingClientRect();renderer.setSize(Math.max(320,r.width),Math.max(320,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};resize();addEventListener('resize',resize);let raf=0,t=0,lastDmg=0,lastAtk=0;
 const attack=()=>{const now=performance.now();if(now-lastAtk<260)return;lastAtk=now;let hit:E|undefined,best=2.5;for(const e of enemies)if(e.alive){const d=e.g.position.distanceTo(player.position);if(d<best){best=d;hit=e}}if(hit){hit.hp--;hit.g.scale.setScalar(1.18);setTimeout(()=>hit&&hit.g.scale.setScalar(1),80);beep(180);if(hit.hp<=0){hit.alive=false;hit.g.visible=false;setKills(v=>v+1);setStageKills(v=>v+1);setXp(v=>v+6+stage);setShards(v=>v+(hit.boss?9:1));beep(hit.boss?80:650)}}};
 const loop=()=>{t+=.016;let dx=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0)+touch.current.x,dz=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0)+touch.current.y,len=Math.hypot(dx,dz)||1;dx/=len;dz/=len;const dash=!!keys.current.shift;keys.current.shift=false;const speed=dash?.19:.075;if(dash)beep(420);player.position.x=THREE.MathUtils.clamp(player.position.x+dx*speed,-12,12);player.position.z=THREE.MathUtils.clamp(player.position.z+dz*speed,-9,8);if(dx||dz)player.rotation.y=Math.atan2(dx,dz);body.position.y=1.05+Math.sin(t*8)*.025;if(keys.current[' ']||keys.current.j){keys.current[' ']=false;keys.current.j=false;attack()}
 for(const e of enemies)if(e.alive){const ex=player.position.x-e.g.position.x,ez=player.position.z-e.g.position.z,d=Math.hypot(ex,ez)||1,f=e.boss?.006:e.type==='brute'?.008:e.type==='caster'?.0045:.012;e.g.position.x+=ex/d*f;e.g.position.z+=ez/d*f;e.g.position.y=Math.sin(t*2+e.g.position.x)*.08;e.g.rotation.y+=.01;if(d<1.35&&performance.now()-lastDmg>450){lastDmg=performance.now();setHp(v=>Math.max(0,v-(e.boss?8:e.type==='brute'?5:3)))}}
 if(hp<=0){setHp(100);setToast('RECOVERED')}const target=new THREE.Vector3(player.position.x*.25,0,player.position.z*.16);camera.position.lerp(new THREE.Vector3(target.x,8.5,11+target.z),.045);camera.lookAt(target);renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);renderer.dispose();el.innerHTML=''}},[screen,stage]);
 const stat=(effect:Skill['effect'])=>Object.entries(levels).reduce((n,[id,lv])=>n+(skills[+id-1]?.effect===effect?lv:0),0),need=stages[stage-1].enemies+(stages[stage-1].boss?1:0);
 const buy=(id:number)=>{const s=skills[id-1],lv=levels[id]||0;if(lv>=s.max||shards<s.cost||(s.prereq!==null&&(levels[s.prereq]||0)<1))return;setShards(v=>v-s.cost);setLevels(v=>({...v,[id]:lv+1}));beep(880);setToast(`${s.name} → Lv.${lv+1}`);setTimeout(()=>setToast(''),1000)};
 const clear=()=>{if(stageKills<need){setToast(`DEFEAT ${need-stageKills} MORE TARGETS`);setTimeout(()=>setToast(''),1200);return}setShards(v=>v+stages[stage-1].reward);if(stage<34){setStage(v=>v+1);setStageKills(0);setXp(0);setHp(100);setToast('STAGE CLEAR');beep(880)}else{setToast('CAMPAIGN COMPLETE');beep(80)}setTimeout(()=>setToast(''),1500)};
 return <main className="shell"><header><div><div className="brand">K3RITO // SHADOWFALL</div><div className="sub">3D ACTION RPG · SECTOR {String(stage).padStart(2,'0')} / 34 · {stages[stage-1].biome}</div></div><nav><button onClick={()=>setScreen('play')} className={screen==='play'?'active':''}>PLAY</button><button onClick={()=>setScreen('map')} className={screen==='map'?'active':''}>MAP</button><button onClick={()=>setScreen('skills')} className={screen==='skills'?'active':''}>SKILLS <b>120</b></button></nav></header>
 {screen==='play'&&<section className="game"><div className="hud"><span>HP <i>{Math.round(hp)}</i></span><span>XP <i>{xp}</i></span><span>SHARDS <i>{shards}</i></span><span>KILLS <i>{stageKills}/{need}</i></span><span className="stage">DMG +{stat('damage')}% · SPD +{stat('speed')}%</span></div><div ref={mount} className="threeGame" onTouchStart={e=>{const t=e.touches[0],r=e.currentTarget.getBoundingClientRect();touch.current={x:(t.clientX-r.left-r.width/2)/(r.width/2),y:(t.clientY-r.top-r.height/2)/(r.height/2)}}} onTouchEnd={()=>touch.current={x:0,y:0}}/><div className="touchControls"><button onTouchStart={()=>keys.current.shift=true}>DASH</button><button onTouchStart={()=>keys.current.j=true}>ATTACK</button></div><div className="actions"><button onClick={clear}>EXTRACT / CLEAR</button><button onClick={()=>setScreen('skills')}>OPEN SKILL TREE</button></div><div className="controls">WASD / ARROWS MOVE · SHIFT DASH · SPACE / J ATTACK · TOUCH DRAG MOVE</div></section>}
 {screen==='map'&&<section className="panel"><h1>THE SHADOWFALL CAMPAIGN</h1><p>34 distinct sectors · 8 biome themes · boss encounters at 5, 10, 15, 20, 25, 30 and 34.</p><div className="grid">{stages.map(s=><button key={s.id} disabled={s.id>stage} onClick={()=>{setStage(s.id);setStageKills(0);setScreen('play')}} className={s.id===stage?'selected':''}><strong>{String(s.id).padStart(2,'0')}</strong><span>{s.name}</span><small>{s.biome}{s.boss?' · BOSS':''}</small></button>)}</div></section>}
 {screen==='skills'&&<section className="panel skills"><div className="skillHead"><div><h1>ASCENSION MATRIX</h1><p>120 nodes · 12 branches · 5 levels. Each node requires the previous node and contributes to combat stats.</p></div><strong>{shards} SHARDS</strong></div><div className="skillGrid">{skills.map(s=>{const lv=levels[s.id]||0,locked=s.prereq!==null&&(levels[s.prereq]||0)<1;return <button key={s.id} disabled={locked||lv>=s.max||shards<s.cost} onClick={()=>buy(s.id)} className={`${lv?'owned ':''}${locked?'locked':''}`}><em>{String(s.id).padStart(3,'0')} · {s.branch}</em><b>{s.name}</b><span>{locked?'LOCKED':`+${s.effect} · level ${lv}/${s.max}`}</span><small>{lv>=s.max?'MAX':`${s.cost} ◆`}</small></button>})}</div></section>}
 {toast&&<div className="toast">{toast}</div>}<footer>PROCEDURAL THREE.JS WORLD · 34 SECTORS · 120 SKILLS · BOSS SYSTEM · TOUCH CONTROLS · LOCAL SAVE · K3RITO</footer></main>;
}