'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {effectLabel,skills,stages,type SkillEffect} from '../lib/gameData';

type Enemy={g:THREE.Group;hp:number;max:number;boss:boolean;type:string;alive:boolean;cool:number};
const SAVE='shadowfall-save';
function sfx(freq:number,duration=.12){try{const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.type=freq<150?'sawtooth':'square';o.frequency.value=freq;g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+duration);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+duration)}catch{}}
export default function Game(){
 const mount=useRef<HTMLDivElement>(null),keys=useRef<Record<string,boolean>>({}),touch=useRef({x:0,y:0});
 const [screen,setScreen]=useState<'play'|'map'|'skills'>('play'),[stage,setStage]=useState(1),[xp,setXp]=useState(0),[shards,setShards]=useState(20),[kills,setKills]=useState(0),[stageKills,setStageKills]=useState(0),[hp,setHp]=useState(100),[levels,setLevels]=useState<Record<number,number>>({1:1}),[toast,setToast]=useState('');
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(SAVE)||'null');if(d){setStage(d.stage||1);setXp(d.xp||0);setShards(d.shards??20);setKills(d.kills||0);setStageKills(d.stageKills||0);setHp(d.hp??100);setLevels(d.levels||{1:1})}}catch{}},[]);
 useEffect(()=>{localStorage.setItem(SAVE,JSON.stringify({stage,xp,shards,kills,stageKills,hp,levels}))},[stage,xp,shards,kills,stageKills,hp,levels]);
 useEffect(()=>{const d=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;if(e.key==='Escape')setScreen('play')},u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false;addEventListener('keydown',d);addEventListener('keyup',u);return()=>{removeEventListener('keydown',d);removeEventListener('keyup',u)}},[]);
 const stat=(effect:SkillEffect)=>Object.entries(levels).reduce((n,[id,lv])=>n+(skills[+id-1]?.effect===effect?lv*skills[+id-1].value:0),0);
 const buy=(id:number)=>{const s=skills[id-1],lv=levels[id]||0;if(lv>=s.max||shards<s.cost||(s.prereq!==null&&(levels[s.prereq]||0)<1))return;setShards(v=>v-s.cost);setLevels(v=>({...v,[id]:lv+1}));sfx(880);setToast(`${s.name}  ·  LV.${lv+1}`);setTimeout(()=>setToast(''),900)};
 useEffect(()=>{if(screen!=='play'||!mount.current)return;const el=mount.current,cfg=stages[stage-1],scene=new THREE.Scene();scene.background=new THREE.Color(0x050711);scene.fog=new THREE.FogExp2(0x070a16,.032);const camera=new THREE.PerspectiveCamera(48,1,.1,140),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);
 const hemi=new THREE.HemisphereLight(0xb9c6ff,0x10121c,1.5);scene.add(hemi);const sun=new THREE.DirectionalLight(0xdde5ff,3.2);sun.position.set(5,12,6);sun.castShadow=true;scene.add(sun);const glow=new THREE.PointLight(cfg.color,18,24);glow.position.set(-4,4,-4);scene.add(glow);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(34,26),new THREE.MeshStandardMaterial({color:0x0d1220,roughness:.86,metalness:.16}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(34,34,cfg.color,0x151a2a);grid.material.transparent=true;grid.material.opacity=.2;scene.add(grid);
 const player=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,1.05,6,10),new THREE.MeshStandardMaterial({color:0xdce7ff,metalness:.72,roughness:.25})),helm=new THREE.Mesh(new THREE.SphereGeometry(.46,16,10),new THREE.MeshStandardMaterial({color:0x111729,metalness:.9,roughness:.18,emissive:0x101a40})),visor=new THREE.Mesh(new THREE.BoxGeometry(.34,.06,.08),new THREE.MeshBasicMaterial({color:cfg.color})),blade=new THREE.Mesh(new THREE.BoxGeometry(.12,1.55,.09),new THREE.MeshStandardMaterial({color:0xd6e5ff,emissive:cfg.color,emissiveIntensity:.55,metalness:.92,roughness:.16}));body.position.y=1.05;helm.position.y=1.9;helm.scale.y=.82;visor.position.set(0,1.94,.42);blade.position.set(.72,1.25,.05);blade.rotation.z=-.48;[body,helm,blade].forEach(m=>m.castShadow=true);player.add(body,helm,visor,blade);scene.add(player);
 const enemies:Enemy[]=[];const makeEnemy=(i:number,boss=false)=>{const type=boss?'boss':i%7===0?'brute':i%5===0?'caster':'stalker',g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:boss?cfg.color:[0xc43b70,0x8c4dff,0x2db7aa,0xff7048][i%4],roughness:.42,metalness:.35,emissive:boss?cfg.color:0,emissiveIntensity:boss?.25:0}),geo=boss?new THREE.IcosahedronGeometry(1.4,1):type==='brute'?new THREE.DodecahedronGeometry(.76,1):new THREE.IcosahedronGeometry(.56,1),core=new THREE.Mesh(geo,mat);core.position.y=boss?1.3:.62;core.castShadow=true;g.add(core);if(type==='caster'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.055,8,24),new THREE.MeshBasicMaterial({color:cfg.color}));ring.rotation.x=Math.PI/2;ring.position.y=.65;g.add(ring)}if(boss){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.65,.045,8,32),new THREE.MeshBasicMaterial({color:cfg.color,transparent:true,opacity:.7}));ring.rotation.x=Math.PI/2;ring.position.y=.15;g.add(ring)}g.position.set(((i*3.7)%17)-8.5,0,-((i*2.15)%10)-1);scene.add(g);const max=boss?12:type==='brute'?3:1;enemies.push({g,hp:max,max,boss,type,alive:true,cool:0})};
 for(let i=0;i<Math.min(16,cfg.enemies);i++)makeEnemy(i);if(cfg.boss)makeEnemy(99,true);
 const fx=new THREE.Group();scene.add(fx);const burst=(pos:THREE.Vector3,color:number)=>{for(let i=0;i<9;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.045,5,5),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos);m.userData={life:.45,v:new THREE.Vector3((Math.random()-.5)*.12,.03+Math.random()*.1,(Math.random()-.5)*.12)};fx.add(m)}};
 const props=new THREE.Group();for(let i=0;i<30;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.3+(i%3)*.13),new THREE.MeshStandardMaterial({color:cfg.color,roughness:.92,transparent:true,opacity:.18+(i%4)*.06}));rock.scale.y=.5+(i%5)*.3;rock.position.set(((i*5.1)%29)-14.5,rock.scale.y*.35,((i*3.7)%21)-10);rock.castShadow=true;props.add(rock)}scene.add(props);
 const resize=()=>{const r=el.getBoundingClientRect();renderer.setSize(Math.max(320,r.width),Math.max(320,r.height),false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};resize();addEventListener('resize',resize);let raf=0,t=0,lastDmg=0,lastAtk=0;const speed=.075+stat('speed')/1000,damage=1+stat('damage')/100,range=2.5+stat('range'),armor=Math.min(.7,stat('armor')/100),crit=Math.min(.6,stat('crit')/100),xpMult=1+stat('xp')/100;
 const attack=()=>{const now=performance.now();if(now-lastAtk<230)return;lastAtk=now;let hit:Enemy|undefined,best=range;for(const e of enemies)if(e.alive){const d=e.g.position.distanceTo(player.position);if(d<best){best=d;hit=e}}if(!hit)return;let amount=damage*(Math.random()<crit?2:1);hit.hp-=amount;burst(hit.g.position,cfg.color);hit.g.scale.setScalar(1.2);setTimeout(()=>hit&&hit.g.scale.setScalar(1),70);sfx(180);if(hit.hp<=0){hit.alive=false;hit.g.visible=false;setKills(v=>v+1);setStageKills(v=>v+1);setXp(v=>v+Math.round((6+stage)*xpMult));setShards(v=>v+(hit.boss?9:1));burst(hit.g.position,hit.boss?0xffffff:cfg.color);sfx(hit.boss?80:650)}};
 const loop=()=>{t+=.016;let dx=(keys.current.d||keys.current.arrowright?1:0)-(keys.current.a||keys.current.arrowleft?1:0)+touch.current.x,dz=(keys.current.s||keys.current.arrowdown?1:0)-(keys.current.w||keys.current.arrowup?1:0)+touch.current.y,len=Math.hypot(dx,dz)||1;dx/=len;dz/=len;const dash=!!keys.current.shift;keys.current.shift=false;const v=(dash?.2:speed);if(dash)sfx(420);player.position.x=THREE.MathUtils.clamp(player.position.x+dx*v,-13,13);player.position.z=THREE.MathUtils.clamp(player.position.z+dz*v,-9,8);if(dx||dz)player.rotation.y=Math.atan2(dx,dz);body.position.y=1.05+Math.sin(t*8)*.025;if(keys.current[' ']||keys.current.j){keys.current[' ']=false;keys.current.j=false;attack()}
 for(const e of enemies)if(e.alive){const ex=player.position.x-e.g.position.x,ez=player.position.z-e.g.position.z,d=Math.hypot(ex,ez)||1,f=e.boss?.006:e.type==='brute'?.008:e.type==='caster'?.0045:.012;e.g.position.x+=ex/d*f;e.g.position.z+=ez/d*f;e.g.position.y=Math.sin(t*2+e.g.position.x)*.08;e.g.rotation.y+=.01;if(e.type==='caster'&&e.cool<=0&&d<5){e.cool=2.2;burst(player.position,0xff7048)}e.cool-=.016;if(d<1.35&&performance.now()-lastDmg>450){lastDmg=performance.now();setHp(v=>Math.max(0,v-Math.max(1,(e.boss?8:e.type==='brute'?5:3)*(1-armor))))}}
 fx.children.forEach(o=>{const m=o as THREE.Mesh;const u=m.userData;u.life-=.016;m.position.add(u.v);m.scale.multiplyScalar(.97);if(u.life<=0)fx.remove(m)});if(hp<=0){player.position.set(0,0,4);setHp(100);setToast('RECOVERED');sfx(300)}const target=new THREE.Vector3(player.position.x*.25,0,player.position.z*.16);camera.position.lerp(new THREE.Vector3(target.x,8.5,11+target.z),.045);camera.lookAt(target);renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);renderer.dispose();el.innerHTML=''}},[screen,stage,levels]);
 const need=stages[stage-1].enemies+(stages[stage-1].boss?1:0);
 const clear=()=>{if(stageKills<need){setToast(`DEFEAT ${need-stageKills} MORE TARGETS`);setTimeout(()=>setToast(''),1200);return}setShards(v=>v+stages[stage-1].reward);if(stage<34){setStage(v=>v+1);setStageKills(0);setXp(0);setHp(100);setToast('STAGE CLEAR');sfx(880)}else{setToast('CAMPAIGN COMPLETE');sfx(80)}setTimeout(()=>setToast(''),1500)};
 return <main className="shell"><header><div><div className="brand">K3RITO // SHADOWFALL</div><div className="sub">3D ACTION RPG · SECTOR {String(stage).padStart(2,'0')} / 34 · {stages[stage-1].biome}</div></div><nav><button onClick={()=>setScreen('play')} className={screen==='play'?'active':''}>PLAY</button><button onClick={()=>setScreen('map')} className={screen==='map'?'active':''}>MAP</button><button onClick={()=>setScreen('skills')} className={screen==='skills'?'active':''}>SKILLS <b>120</b></button></nav></header>
 {screen==='play'&&<section className="game"><div className="hud"><span>HP <i>{Math.round(hp)}</i></span><span>XP <i>{xp}</i></span><span>SHARDS <i>{shards}</i></span><span>KILLS <i>{stageKills}/{need}</i></span><span className="stage">DMG +{Math.round(stat('damage'))}% · SPD +{Math.round(stat('speed'))}% · ARM {Math.round(stat('armor'))}%</span></div><div ref={mount} className="threeGame" onTouchStart={e=>{const t=e.touches[0],r=e.currentTarget.getBoundingClientRect();touch.current={x:(t.clientX-r.left-r.width/2)/(r.width/2),y:(t.clientY-r.top-r.height/2)/(r.height/2)}}} onTouchEnd={()=>touch.current={x:0,y:0}}/><div className="touchControls"><button onTouchStart={()=>keys.current.shift=true}>DASH</button><button onTouchStart={()=>keys.current.j=true}>ATTACK</button></div><div className="actions"><button onClick={clear}>EXTRACT / CLEAR</button><button onClick={()=>setScreen('skills')}>OPEN SKILL TREE</button></div><div className="controls">WASD / ARROWS MOVE · SHIFT DASH · SPACE / J ATTACK · TOUCH DRAG MOVE</div></section>}
 {screen==='map'&&<section className="panel"><h1>THE SHADOWFALL CAMPAIGN</h1><p>34 sectors · 8 biome themes · escalating enemies · 7 boss encounters.</p><div className="grid">{stages.map(s=><button key={s.id} disabled={s.id>stage} onClick={()=>{setStage(s.id);setStageKills(0);setScreen('play')}} className={s.id===stage?'selected':''}><strong>{String(s.id).padStart(2,'0')}</strong><span>{s.name}</span><small>{s.biome}{s.boss?' · BOSS':''}</small></button>)}</div></section>}
 {screen==='skills'&&<section className="panel skills"><div className="skillHead"><div><h1>ASCENSION MATRIX</h1><p>120 nodes · 12 branches · 5 levels. Every upgrade modifies combat.</p></div><strong>{shards} SHARDS</strong></div><div className="skillStats"><span>DMG +{Math.round(stat('damage'))}%</span><span>SPD +{Math.round(stat('speed'))}%</span><span>RANGE +{stat('range').toFixed(1)}</span><span>ARM +{Math.round(stat('armor'))}%</span><span>CRIT +{Math.round(stat('crit'))}%</span><span>XP +{Math.round(stat('xp'))}%</span></div><div className="skillGrid">{skills.map(s=>{const lv=levels[s.id]||0,locked=s.prereq!==null&&(levels[s.prereq]||0)<1;return <button key={s.id} disabled={locked||lv>=s.max||shards<s.cost} onClick={()=>buy(s.id)} className={`${lv?'owned ':''}${locked?'locked':''}`}><em>{String(s.id).padStart(3,'0')} · {s.branch}</em><b>{s.name}</b><span>{locked?'LOCKED':`+${s.value}${s.effect==='range'? '':'%'} ${effectLabel(s.effect)} · ${lv}/${s.max}`}</span><small>{lv>=s.max?'MAX':`${s.cost} ◆`}</small></button>})}</div></section>}
 {toast&&<div className="toast">{toast}</div>}<footer>PROCEDURAL THREE.JS WORLD · 34 SECTORS · 120 SKILLS · WEB AUDIO · LOCAL SAVE · K3RITO</footer></main>;
}
